spring.application.name=usuarios-roles-bff

server.port=8080

azure.functions.base-url=${AZURE_FUNCTIONS_BASE_URL:http://localhost:7071/api}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always