-- =====================================================================
-- Semana 8 · Tablas de los consumidores de eventos (Azure Event Grid)
-- Ejecutar en Oracle después de usuarios_roles.sql
-- =====================================================================

-- EVENT STORE: copia inmutable de cada evento publicado en el topic.
-- La escribe la función "auditoria-eventos". No tiene llaves foráneas
-- para que el historial se conserve aunque se eliminen usuarios o roles.
CREATE TABLE AUDITORIA_EVENTOS (
    ID_EVENTO VARCHAR2(64) NOT NULL,
    TIPO_EVENTO VARCHAR2(60) NOT NULL,
    SUBJECT VARCHAR2(150),
    FECHA_EVENTO TIMESTAMP NOT NULL,
    DATOS CLOB,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_AUDITORIA_EVENTOS
        PRIMARY KEY (ID_EVENTO),

    CONSTRAINT CK_AUDITORIA_DATOS_JSON
        CHECK (DATOS IS JSON)
);

CREATE INDEX IX_AUDITORIA_SUBJECT
    ON AUDITORIA_EVENTOS (SUBJECT, FECHA_EVENTO);

CREATE INDEX IX_AUDITORIA_TIPO
    ON AUDITORIA_EVENTOS (TIPO_EVENTO, FECHA_EVENTO);


-- BANDEJA DE NOTIFICACIONES: avisos generados por la función
-- "notificaciones-eventos". ID_EVENTO es único para que un reintento de
-- Event Grid no duplique el aviso.
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_EVENTO VARCHAR2(64) NOT NULL,
    TIPO_EVENTO VARCHAR2(60) NOT NULL,
    DESTINATARIO VARCHAR2(150) NOT NULL,
    ASUNTO VARCHAR2(200) NOT NULL,
    MENSAJE VARCHAR2(1000) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_NOTIFICACIONES
        PRIMARY KEY (ID_NOTIFICACION),

    CONSTRAINT UQ_NOTIFICACIONES_EVENTO
        UNIQUE (ID_EVENTO)
);

CREATE INDEX IX_NOTIFICACIONES_DESTINATARIO
    ON NOTIFICACIONES (DESTINATARIO, FECHA_CREACION);

COMMIT;
